# Generated by Django 4.2.5 on 2023-09-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaNatural',
            fields=[
                ('PersonaNaturalId', models.AutoField(primary_key=True, serialize=False)),
                ('NumDocumento', models.CharField(max_length=20)),
                ('Nombres', models.CharField(max_length=100)),
                ('ApellidoPaterno', models.CharField(max_length=100)),
                ('ApellidoMaterno', models.CharField(max_length=100)),
                ('FechaNacimiento', models.DateField()),
                ('Direccion', models.CharField(max_length=200)),
                ('Correo', models.EmailField(max_length=254)),
                ('Telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='MiModelo',
        ),
    ]
