# Generated by Django 4.2.5 on 2023-09-20 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('AlumnoId', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Catalogo_Alumno',
            },
        ),
        migrations.CreateModel(
            name='CargoModel',
            fields=[
                ('CargoId', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('FechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('CodUsuario', models.CharField(max_length=15)),
                ('EstadoRegistro', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'catalogo_cargo',
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('EstadoCivilId', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Catalogo_EstadoCivil',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('GeneroId', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Catalogo_Genero',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumentoIdentidad',
            fields=[
                ('TipoDocumentoIdentidadId', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo', models.CharField(max_length=30)),
                ('Alias', models.CharField(max_length=30)),
                ('Descripcion', models.CharField(max_length=150)),
                ('EsEmpresa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Catalogo_TipoDocumentoIdentidad',
            },
        ),
        migrations.CreateModel(
            name='Ubigeo',
            fields=[
                ('UbigeoId', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo', models.CharField(max_length=6, unique=True)),
                ('Nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Catalogo_Ubigeo',
            },
        ),
        migrations.CreateModel(
            name='PersonaNaturalModel',
            fields=[
                ('PersonaNaturalId', models.AutoField(primary_key=True, serialize=False)),
                ('NumDocumento', models.CharField(default='', max_length=255)),
                ('Nombres', models.CharField(default='', max_length=255)),
                ('ApellidoPaterno', models.CharField(default='', max_length=255)),
                ('ApellidoMaterno', models.CharField(default='', max_length=255)),
                ('FechaNacimiento', models.DateField(default=None)),
                ('Direccion', models.CharField(default='', max_length=255)),
                ('Telefono', models.CharField(default='', max_length=255)),
                ('Correo', models.EmailField(default='', max_length=255)),
                ('FechaRegistro', models.DateField(default=None)),
                ('CodUsuario', models.CharField(default='', max_length=255)),
                ('EstadoRegistro', models.BooleanField(default=True)),
                ('EstadoCivilId', models.ForeignKey(db_column='EstadoCivilId', on_delete=django.db.models.deletion.CASCADE, to='ApiPrueba.estadocivil')),
                ('GeneroId', models.ForeignKey(db_column='GeneroId', on_delete=django.db.models.deletion.CASCADE, to='ApiPrueba.genero')),
                ('TipoDocumentoIdentidad', models.ForeignKey(db_column='TipoDocumentoIdentidadId', on_delete=django.db.models.deletion.CASCADE, to='ApiPrueba.tipodocumentoidentidad')),
                ('UbigeoId', models.ForeignKey(db_column='UbigeoId', on_delete=django.db.models.deletion.CASCADE, to='ApiPrueba.ubigeo')),
            ],
            options={
                'db_table': 'Catalogo_PersonaNatural',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('CursoId', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255)),
                ('AlumnoId', models.ForeignKey(db_column='AlumnoId', on_delete=django.db.models.deletion.CASCADE, to='ApiPrueba.alumno')),
            ],
            options={
                'db_table': 'Catalogo_Curso',
            },
        ),
    ]
