# Generated by Django 4.2.5 on 2023-09-21 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiPrueba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('TipodocumentoId', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('PersonaId', models.AutoField(primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=255)),
                ('Apellidos', models.CharField(max_length=255)),
                ('TipodocumentoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiPrueba.tipodocumento')),
            ],
        ),
    ]
