# Generated by Django 4.2.5 on 2023-09-19 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiPrueba', '0002_cabeceraitem_detalleitem_remove_detalle_cabecera_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabecera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255)),
                ('Cabecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ApiPrueba.cabecera')),
            ],
        ),
        migrations.RemoveField(
            model_name='detalleitem',
            name='CabeceraId',
        ),
        migrations.DeleteModel(
            name='CabeceraItem',
        ),
        migrations.DeleteModel(
            name='DetalleItem',
        ),
    ]
