# Generated by Django 4.2.5 on 2023-09-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiPrueba', '0002_tipodocumento_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personanaturalmodel',
            name='FechaRegistro',
            field=models.DateTimeField(default=None),
        ),
    ]
