# Generated by Django 4.2.5 on 2023-09-20 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiPrueba', '0003_cabecera_detalle_remove_detalleitem_cabeceraid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='cabecera',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.DeleteModel(
            name='Detalle',
        ),
        migrations.AddField(
            model_name='detalleitem',
            name='cabecera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiPrueba.cabecera'),
        ),
    ]
