# Generated by Django 4.2.5 on 2023-09-20 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiPrueba', '0004_detalleitem_rename_nombre_cabecera_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleitem',
            name='cabecera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ApiPrueba.cabecera'),
        ),
    ]
