# Generated by Django 4.2.5 on 2023-09-20 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiPrueba', '0005_alter_detalleitem_cabecera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('ProductoId', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductosPrecio',
            fields=[
                ('ProductoPrecioId', models.AutoField(primary_key=True, serialize=False)),
                ('NombreUnidadMedida', models.CharField(max_length=255)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='ApiPrueba.producto')),
            ],
        ),
        migrations.RemoveField(
            model_name='detalleitem',
            name='cabecera',
        ),
        migrations.DeleteModel(
            name='Cabecera',
        ),
        migrations.DeleteModel(
            name='DetalleItem',
        ),
    ]
