# Generated by Django 4.2.5 on 2023-09-20 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiPrueba', '0006_producto_productosprecio_remove_detalleitem_cabecera_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_orden', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('estado_orden', models.CharField(max_length=50)),
                ('fecha_emision', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OrdenPedidoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.IntegerField()),
                ('cantidad_unidad_medida', models.PositiveIntegerField()),
                ('precio_unidad_medida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_solicitado', models.PositiveIntegerField()),
                ('cantidad_faltante', models.PositiveIntegerField()),
                ('cantidad_atendido', models.PositiveIntegerField()),
                ('enlazado', models.BooleanField()),
                ('es_atendido', models.BooleanField()),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ApiPrueba.ordenpedido')),
            ],
        ),
        migrations.RemoveField(
            model_name='productosprecio',
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='ProductosPrecio',
        ),
    ]
