# Generated by Django 4.2.5 on 2023-09-20 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiPrueba', '0007_ordenpedido_ordenpedidodetalle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('AlumnoId', models.AutoField(primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('CursoId', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255)),
                ('Alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiPrueba.alumno')),
            ],
        ),
        migrations.RemoveField(
            model_name='ordenpedidodetalle',
            name='orden_pedido',
        ),
        migrations.DeleteModel(
            name='OrdenPedido',
        ),
        migrations.DeleteModel(
            name='OrdenPedidoDetalle',
        ),
    ]
