# Generated by Django 4.2.5 on 2023-09-20 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiPrueba', '0008_alumno_curso_remove_ordenpedidodetalle_orden_pedido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='Nombres',
            new_name='Nombre',
        ),
    ]
