# Generated by Django 4.2.5 on 2023-09-20 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiPrueba', '0009_rename_nombres_alumno_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='Alumno',
            new_name='AlumnoId',
        ),
    ]
