# Generated by Django 4.2.5 on 2023-09-20 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiPrueba', '0010_rename_alumno_curso_alumnoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='AlumnoId',
            field=models.ForeignKey(db_column='AlumnoId', on_delete=django.db.models.deletion.CASCADE, to='ApiPrueba.alumno'),
        ),
    ]
